config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5

  resources :movies do
    member do
      post 'review'
    end
  end

<<<<<<< HEAD
  post '/posts/:id/comments' => 'posts#comments'

  get '/admin/index'
  get '/admin/posts'
  get '/admin/reviews'
  get '/posts/privacy' => 'posts#privacy' # 이거 아래에있으면 동작 안함

  put '/admin/to_manager/:id' => 'admin#to_manager'
  put '/admin/to_user/:id' => 'admin#to_user'

  put '/admin/reviews_destroy/:id' => 'admin#reviews_destroy'
  delete '/admin/posts_destroy/:id' => 'admin#posts_destroy'

=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5

  resources :posts
  devise_for :users

  root 'movies#index'

  get 'movies/show/:id' => 'movies#show'

  get 'movies' => 'movies#index'

<<<<<<< HEAD
  get 'home/index' => 'home#index'

=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # belongs_to :user_id
  # 레퍼런스 하면 자동으로 생성되는데 이거떔에 댓글 안써짐
  belongs_to :user # 이렇게 해줘야 맞음
  belongs_to :post
end

app/models/mobie.rb
class Mobie < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
<<<<<<< HEAD
  # has_many :movies
  has_many :reviews

  mount_uploader :poster, PhotoUploader
=======
  has_many :movies
  has_many :reviews

>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
  def number
    self.reviews.count
  end

  def average
    sum = 0
    self.reviews.each do |review| # self하면 본인 객체가 들어감
    sum += review.rating
    end
    if self.reviews.count == 0
      0
    else
    sum.to_f / self.reviews.count
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
<<<<<<< HEAD
  mount_uploader :image, PhotoUploader # 업로더를 다른 모델이 쓸 수 있게 함

  belongs_to :user
  has_many :comments

=======
  belongs_to :user
  belongs_to :movie
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
<<<<<<< HEAD
  belongs_to :movie
=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :reviews
<<<<<<< HEAD
  has_many :comments
=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  # layout 'admin'
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @users = User.all
  end

  def posts
    @posts = Post.all
  end

  def movies
    @movies = Movie.all
  end

  def reviews
    @reviews = Review.all
  end

  def posts_destroy
    # 특정 게시글을 지운다.
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :back, notice: "#{params[:id]}번 게시글이 삭제되었습니다."
  end

  def reviews_destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to :back, notice: "#{params[:id]}번 게시글이 삭제되었습니다."
  end

  def to_manager
    @user = User.find(params[:id])
    @user.update(
      role: "manager"
    )
    flash[:notice] = "매니저로 승급 되었습니다"
    redirect_to :back
  end

  def to_user
    @user = User.find(params[:id])
    @user.update(
      role: "user"
    )
    flash[:notice] = "양민이 되었습니다"
    redirect_to :back
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_admin
<<<<<<< HEAD
    user_signed_in? && current_user.role == "admin"
=======
    user_signed_in? && current_user.is_admin?
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
  end

  def get_out
    redirect_to root_path unless check_admin
  end


  helper_method :check_admin

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end



end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :get_out, except: [:index, :show, :review]

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new

  end

  def create
    Movie.create(
      title: params[:title],
      poster: params[:poster],
      genre: params[:genre],
      nation: params[:nation],
      director: params[:director]
    )
<<<<<<< HEAD
    # redirect_to '/' 
=======
    # redirect_to '/'
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
    redirect_to root_path
  end

  def edit

  end

  def update

  end

  def review
    Review.create(
      rating: params[:rating],
      comment: params[:comment],
      user_id: current_user.id,
      movie_id: params[:id]
    )
    redirect_to :back
  end

<<<<<<< HEAD


=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
<<<<<<< HEAD
  before_action :authenticate_user!, except: [:index, :privacy] #인덱스 빼고 다
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # 이거 쓰면 레이아웃 적용 안됨
  # layout false

=======
  before_action :authenticate_user!, except: [:index] #인덱스 빼고 다
  before_action :set_post, only: [:show, :edit, :update, :destroy]

>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
<<<<<<< HEAD
    # @comments = Comment.all
    # @post 안에 들어있어서 필요 없음
=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

<<<<<<< HEAD
  def comments
    Comment.create(
      content: params[:content],
      user_id: current_user.id,
      post_id: params[:id]
    )
    # comment.save
    redirect_to :back

  end

  def privacy
    # render Rails.root.join('app', 'views', 'etc', 'promise.html.erb')
    # render nothing: true
    render template:'etc/promise'
  end

=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
<<<<<<< HEAD
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end

=======

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
end

app/helpers/application_helper.rb
module ApplicationHelper
<<<<<<< HEAD
  # def current_user
  #   # current_user
  # end
=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/index.html.erb

<main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
<h1>관리자 페이지 입니다</h1>
<!-- 여기를 감싸고있는 admin레이아웃을 먼저 찾음 -->
  <h2>유저 현황</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>이메일</th>
          <th>닉네임</th>
          <th>역할</th>
          <th>역할 변경</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
        <td><%= user.email %></td>
        <td><%= user.nickname%></td>
        <td><%= user.role%></td>
        <td><%= link_to "[매니저로]", "/admin/to_manager/#{user.id}",class: "btn btn-primary btn-lg", method: :put, data: {confirm: "매니저로 하시겠습니까?"} %></td>
        <td><%= link_to "[양민으로]", "/admin/to_user/#{user.id}",class: "btn btn-primary btn-lg",  method: :put, data: {confirm: "양민으로 하시겠습니까?"}  %></td>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</main>

app/views/admin/posts.html.erb

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
     <h1>관리자 페이지 입니다</h1>
      <h2>게시판 현황</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>제목</th>
              <th>내용</th>
              <th>글쓴이</th>
              <th>그림</th>
              <th>삭제</th>

            </tr>
          </thead>

          <tbody>

            <% @posts.each do |post| %>
            <tr>
            <td><%= post.id %></td>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td><%= post.user.nickname %></td>
            <td><img src="<%= post.image.thumb %>"></td>
            <td><%= link_to "삭제", "/admin/posts_destroy/#{post.id}", method: :put, data: {confirm: "지우기를 하시겠습니까?"}%></td>

            </tr>
            <% end %>

          </tbody>
        </table>
      </div>
    </main>


</body>
</html>

app/views/admin/reviews.html.erb

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <h1>관리자 페이지 입니다</h1>
      <h2>리뷰 현황</h2>
      <div class="table-responsive">
        <table class="table table-striped">

          <thead>
            <tr>
              <th>#</th>
              <th>영화</th>
              <th>글쓴이</th>
              <th>평점</th>
              <th>리뷰</th>
              <th>삭제</th>
            </tr>
          </thead>

          <tbody>
            
            <% @reviews.each do |review| %>
            <tr>
            <td><%= review.id %></td>
            <td><%= review.movie.title %></td>
            <td><img width="30" height="30" src="<%= review.movie.poster %>"></td>
            <td><%= review.user.nickname %></td>
            <td><%= review.rating %></td>
            <td><%= review.comment %></td>
            <td><%= link_to "삭제", "/admin/reviews_destroy/#{review.id}", method: :put, data: {confirm: "지우기를 하시겠습니까?"}%></td>

            </tr>
            <% end %>

          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


</body>
</html>

app/views/etc/promise.html.erb
<h1>개인정보 처리 방침</h1>

app/views/layouts/_admin_header.html.erb
<header>
<div class="collapse bg-dark" id="navbarHeader">
<div class="container">
  <div class="row">
    <div class="col-sm-8 py-4">
      <h4 class="text-white">왓차</h4>
      <p class="text-muted">영화 평점 사이트 왓챠 입니다. 저희 왓차를 이용하시는 모든 회원님들을 대상으로 평점 주기 이벤트를 실시하고 있습니다. 많은 참여 바랍니다.</p>
    </div>
    <div class="col-sm-4 py-4">
      <h4 class="text-white">Contact</h4>
      <ul class="list-unstyled">
          <li class="text-white"><%= current_user.nickname if user_signed_in? %> 님 안녕하세영?</li>
          <li><%= link_to "게시판", posts_path, class: "text-white" %></li>
          <li><%= link_to "로그아웃", destroy_user_session_path, method: "delete", class: "text-white" %></li>
          <li><%= link_to "로그인", new_user_session_path, class: "text-white" %></li>
      </ul>
    </div>
  </div>
</div>
</div>

<div class="navbar navbar-dark bg-dark">
<div class="container d-flex justify-content-between">
  <a href="/" class="navbar-brand">영화 목록</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
</div>
</header>

app/views/layouts/_admin_sidebar.html.erb

<nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
  <ul class="nav nav-pills flex-column">
    <br><br><br>
    <li class="nav-item">
      <a class="nav-link active" href="/admin/index">관리자 홈피<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/admin/index">유저 관리</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/admin/posts">게시판 관리</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/admin/reviews">리뷰 관리</a>
    </li>
  </ul>
</nav>

app/views/layouts/_header.html.erb
<<<<<<< HEAD

=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
<header>
<div class="collapse bg-dark" id="navbarHeader">
<div class="container">
  <div class="row">
    <div class="col-sm-8 py-4">
      <h4 class="text-white">왓차</h4>
<<<<<<< HEAD
      <p class="text-muted">영화 평점 사이트 왓챠 입니다. 저희 왓차를 이용하시는 모든 회원님들을 대상으로 평점 주기 이벤트를 실시하고 있습니다. 많은 참여 바랍니다.</p>
=======
      <p class="text-muted">왓차차차차창</p>
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
    </div>
    <div class="col-sm-4 py-4">
      <h4 class="text-white">Contact</h4>
      <ul class="list-unstyled">
<<<<<<< HEAD
          <li class="text-white"><%= current_user.nickname if user_signed_in? %> 님 안녕하세영?</li>
=======
          <li class="text-white"><%= current_user.nickname if user_signed_in? %></li>
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
          <li><%= link_to "게시판", posts_path, class: "text-white" %></li>
          <li><%= link_to "로그아웃", destroy_user_session_path, method: "delete", class: "text-white" %></li>
          <li><%= link_to "로그인", new_user_session_path, class: "text-white" %></li>
      </ul>
    </div>
  </div>
</div>
</div>
<<<<<<< HEAD

=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
<div class="navbar navbar-dark bg-dark">
<div class="container d-flex justify-content-between">
  <a href="/" class="navbar-brand">영화 목록</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
</div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>관리자 페이지</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/admin_header' %>
  <div class="container-fluid">
    <div class="row">
  <%= render 'layouts/admin_sidebar' %>
    <p id="notice"><%= flash[:notice] %></p>
      <%= yield %>

    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watcha</title>
  <link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/examples/album/album.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

  <p><%= flash[:notice] %></p>
  <P><%= flash[:alert] %></p>
<<<<<<< HEAD
=======
  <%= link_to "게시판", posts_path%>
  <%= link_to "로그아웃", destroy_user_session_path, method: "delete" %>
  <%= link_to "로그인", new_user_session_path %>
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5

<%= yield %>

</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watcha</title>
  <link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/examples/album/album.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

  <p><%= flash[:notice] %></p>
  <P><%= flash[:alert] %></p>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">왓챠!</h1>
      <p class="lead text-muted">영화 평점 사이트 왓챠</p>
      <p>
        <%= link_to "게시판", posts_path, class: "btn btn-primary" %>
        <%= link_to "영화 추가하기", new_movie_path, class: "btn btn-secondary" if check_admin %>
<<<<<<< HEAD
        <%= link_to "관리자 페이지", "/admin/index" , class: "btn btn-secondary" if check_admin %>
=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
      </p>
    </div>
  </section>

  <div class="album text-muted">
    <div class="container">

      <div class="row">
        <% @movies.each do |movie| %>
        <div class="card">
          <a href="/movies/show/<%= movie.id %>">
          <img height="280px" src="<%= movie.poster %>" alt="Card image cap">
          <p class="card-title">평점 : <%= movie.average == 0 ? "리뷰가 없어영 ㅠ" : movie.average %></p>
          <!-- 트루일때는 앞에꺼 거짓일때는 뒤에꺼 -->
          <p class="card-text">
          <div><%= movie.title %></div>
          </p>
        </a>
        </div>
        <% end %>
      </div>

    </div>
  </div>

</main>

app/views/movies/new.html.erb
<<<<<<< HEAD
<h1>영화 추가하기</h1>

<%= form_tag movies_path method: :post, multipart: true do  %>
제목 : <%= text_field_tag :title %><br>
장르 : <%= text_field_tag :genre %><br>
국가 : <%= text_field_tag :nation %><br>
감독 : <%= text_field_tag :director %><br>
포스터 : <%= text_field_tag :poster %><br>
=======
<%= form_tag movies_path method: :post do  %>
제목 : <%= text_field_tag :title %>
포스트 : <%= text_field_tag :poster %>
장르 : <%= text_field_tag :genre %>
네이션 : <%= text_field_tag :nation %>
감독 : <%= text_field_tag :director %>
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
<%= submit_tag "영화 만들기" %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
<<<<<<< HEAD
  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :image %>
  </div>
=======
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.nickname %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.nickname %>
</p>

<<<<<<< HEAD
<p>
  <strong>Image:</strong>
  <img src="<%= @post.image.small %>">
</p>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<%= form_tag "/posts/#{@post.id}/comments", method: :post do %>
  <%= text_field_tag :content %>
  <%= submit_tag "댓글 쓰기" %>
<% end %>

<% @post.comments.each do |comment| %>
<p>작성자 : <%= comment.user.nickname %></p>
<p>내용 : <%= comment.content %></p>
<% end %>
=======
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
>>>>>>> d776ad36555d0bcbb98e84e500a8907a61ae41d5